### ISSUE TITLE
Installation under node 9.8.0 "Failed at the metricio@1.1.0 start script."

### ISSUE THREAD

**Issue by quistuipater** [metricio/metricio#14]
```
> babel-node app.js

/metricio/app.js:1
(function (exports, require, module, __filename, __dirname) { import { createServer } from 'http';
                                                              ^^^^^^
SyntaxError: Unexpected token import
```

**Comment by dannycroft** [comment]
@quistuipater 

Sorry to hear you were having problems. I've been AFK for a few weeks.

I've had a look and the only way I can get the same output is to remove es2015 presents from the `.babelrc` file or just delete the file. I am using Ubuntu 18.04 though, so maybe this is a Windows file path problem?

Could you try running the following (from inside the metrico folder): `npx babel-node --presets es2015,react -- app.js`

I've tried the installation steps with node v9.8.0, v10.0.0 and v8.10.0. All were successfull. Always from a clean checkout of the latest metricio release.

![metrico-node-v9-8-0](https://user-images.githubusercontent.com/87240/39439287-62d083fc-4ca7-11e8-81cc-425d7a79e1b9.gif)

Could you give me a little more information about your environment, please? Nothing big, just OS name, version etc. Maybe even what steps you took beforehand.

Thanks!

**Comment by dannycroft** [comment]
Closing due to lack of feedback. 

If the none of the above helped then maybe try that latest release :+1:
