### ISSUE TITLE
Error starting Metricio 1.1.0: The "path" argument must be of type string

### ISSUE THREAD

**Issue by mikehamil10** [metricio/metricio#15]
This is a perfectly clean install of Metricio. All I did was download the .zip (following the get started guide), extract it to a folder in my user directory and in Powershell run _npm install_ and then _npm run start_.

I'm on Windows 10 with Node v9.5.0 and NPM v5.6.0

Here's the output:

```
PS C:\Users\Mike\Projects\react\metricio-1.1.0> npm run start

> metricio@1.1.0 start C:\Users\Mike\Projects\react\metricio-1.1.0
> babel-node app.js

path.js:28
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.join (path.js:489:7)
    at Object.<anonymous> (C:/Users/Mike/Projects/react/metricio-1.1.0/config/paths.js:6:20)
    at Module._compile (module.js:660:30)
    at loader (C:\Users\Mike\Projects\react\metricio-1.1.0\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Mike\Projects\react\metricio-1.1.0\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! metricio@1.1.0 start: `babel-node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the metricio@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mike\AppData\Roaming\npm-cache\_logs\2018-05-02T21_49_33_538Z-debug.log
```

Any help would be much appreciated!

**Comment by dannycroft** [comment]
Hey @mikehamil10 

I'll take a look at this for you. To be honest, I use Linux for most of my development and I have a few macs I tested Metricio on without any issues. I think this might be an issue of me not making more of an effort to make sure this was Windows safe. 

Sorry about that. I'll take a look over the next few days and get a new release out ASAP.

**Comment by mikehamil10** [comment]
Hey @dannycroft thanks for the reply! If nothing immediate jumps out at you, I actually think I might know what my problem is -- I don't have Redis installed on this machine. So perhaps the error message just isn't descriptive enough about the underlying issue.

After doing some searching, I can't even seem to find an up-to-date release of Redis on widows...so I will try to do a "clean" test again on OSX and report back!

**Comment by dannycroft** [comment]
Hey @mikehamil10 

I've created a new release which will help Windows users but also clearly state any errors there are with Redis not running or being unavailable. I hope that helps. If you get into any more problems just give me a shout :+1: 

For installing Redis on Windows 10, I can only forward you to a [Medium article ](https://medium.com/@furkanpur/installation-redis-on-windows-10-13fbb055be7c) that looks like it might help. I'm not really a Windows guy, sorry.

v1.2.0 - https://github.com/metricio/metricio/releases/tag/v1.2.0

**Comment by dannycroft** [comment]
Closing :+1:
