### ISSUE TITLE
[QUESTION] - Docker Installation

### ISSUE THREAD

**Issue by casalot** [metricio/metricio#17]
Any docs or plans for docker/docker-compose solution?

**Comment by dannycroft** [comment]
@casalot Yeah, good idea! I don't think that would be to difficult at all. I'll take a look and get an updated version released soon :+1:

**Comment by cwagnello** [comment]
I would like this as well. I'm building a container using docker compose and I need to change what address Redis is being referenced from within `connect-redis`.
