### ISSUE TITLE
ASP Backend with Metrico

### ISSUE THREAD

**Issue by weedkiller** [metricio/metricio#20]
Would be great to work with ASP MVC and Metrico, tooling and widgeting would be easy

**Comment by dannycroft** [comment]
hey @weedkiller 

I'm not super familiar with ASP MVC but what tooling and widgets are you missing? Or perhaps you are referring to integration with Visual Studio etc

Let me know :+1:

**Comment by weedkiller** [comment]
Hi @dannycroft the ASP community is starved for something like this, so I can see adoption as we get mature, so good luck 🥇 

The integration with the VS tooling, and including a template or a sample on how to wrap the html widgets as partials (ASP MVC) or now called view components (ASP CORE)

Here is a [link ](https://stackoverflow.com/questions/23518499/creating-reusable-html-view-components-using-razor-in-asp-net-mvc)to how to simply wrap them up as ASP MVC helpes/partials/vews, when we rwrap it inside 
```
@helper DefaultPanel(string panelTitle, Func<object, object> content)
{
    <div class="Metricao panel">
        <div class="panel-logo">
                <img src="/logo.png" />
            </div>
            <div class="panel-inner">
                <p class="panel-title">@panelTitle</p>
                <div class="panel-content">
                    @content(null)
                </div>
            </div>
    </div>
}
```
_____________________________________
Its also possible/easier with ** ASP CORE View components** like [here](https://www.davepaquette.com/archive/2016/01/02/goodbye-child-actions-hello-view-components.aspx)

```
  @model IEnumerable
  <Widget>
  <h2>What's New</h2>
  <ul>@foreach (var widget in Model)
  {    
      <li><a asp-controller="Widget"            asp-action="View"            asp-route- 
                   id="@Widget.Id">@widget.Title</a>
      </li>
   }
  </ul>

```
