### ISSUE TITLE
Disable caching

### ISSUE THREAD

**Issue by cwagnello** [metricio/metricio#21]
The caching is a good idea for always displaying something if it ever succeeded but I need to know if a service is down. As such I don't want to see a cached result if the service is unreachable for example. I was wondering if there is a way to set a flag in the job to disable caching of certain requests.

**Comment by danielepolencic** [comment]
I sort of share the same concerns/feelings. Also, the original dashing didn't feature a storage layer and it was very easy to set up as a consequence (no need to provision Redis or similar).
